### ISSUE TITLE
[Offtopic] Scxml editor and examples

### ISSUE THREAD

**Issue by alexzhornyak** [Mumbasms/Neo4jBySprinBoot#1]
Excuse me that I am writing here. You were interesting in SCION-SCXML/Lobby about SCXML examples and tutorials. I couldn't email you, so wrote here

Here is the link for examples and tutorial
https://github.com/alexzhornyak/SCXML-tutorial

And here is the link for ScxmlEditor where you may test scxml on the fly
https://github.com/alexzhornyak/ScxmlEditor-Tutorial

**Comment by Mumbasms** [comment]
Oh thanks, Alex. Appreciate your help.  I will go through this information.  Are you there in the lobby too?)   I could not find you there.  Anyway, I am glad to be part of such a supportive group of people :)

- Prashant

**Comment by alexzhornyak** [comment]
Unfortunately I'm not a part of the lobby because of mostly working with Qt SCXML and USCXML but the lobby is associated with Web SCION. But if I see that somebody is interested in good SCXML tools I am glad to share it. So if you have C++ SCXML questions feel free to type me on my mail

Best regards, Alex
